/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/lO3NQbpXST4
 */
import { CardTitle, CardDescription, CardHeader, CardContent, Card } from "@/components/ui/card"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"
import { TableHead, TableRow, TableHeader, TableCell, TableBody, Table } from "@/components/ui/table"

export function history() {
  return (
    <Card>
      <CardHeader>
        <CardTitle>Transaction History</CardTitle>
        <CardDescription>Deposit and withdrawal history for your Binance FX wallet</CardDescription>
      </CardHeader>
      <CardContent className="flex flex-col gap-4">
        <div className="flex items-center gap-4">
          <form className="flex items-center gap-4">
            <Label className="sr-only" htmlFor="search">
              Search
            </Label>
            <Input
              className="w-[200px] sm:w-[300px] md:w-[200px] border-gray-200 dark:border-gray-800"
              id="search"
              placeholder="Search"
              type="search"
            />
            <Button type="submit">Search</Button>
          </form>
          <div className="ml-auto flex items-center gap-2">
            <Button size="sm">Deposit</Button>
            <Button size="sm">Withdraw</Button>
          </div>
        </div>
        <div className="border rounded-lg">
          <Table>
            <TableHeader>
              <TableRow>
                <TableHead className="min-w-[150px]">Transaction</TableHead>
                <TableHead className="min-w-[150px]">Date</TableHead>
                <TableHead className="min-w-[150px]">Type</TableHead>
                <TableHead className="min-w-[150px]">Currency</TableHead>
                <TableHead className="min-w-[150px]">Amount</TableHead>
                <TableHead className="min-w-[150px]">Status</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              <TableRow>
                <TableCell>
                  <div className="font-semibold">#123456789</div>
                </TableCell>
                <TableCell>March 1, 2023 14:20:00</TableCell>
                <TableCell>Deposit</TableCell>
                <TableCell>USDT</TableCell>
                <TableCell>$100.00</TableCell>
                <TableCell>Completed</TableCell>
              </TableRow>
              <TableRow>
                <TableCell>
                  <div className="font-semibold">#987654321</div>
                </TableCell>
                <TableCell>March 1, 2023 14:20:00</TableCell>
                <TableCell>Withdrawal</TableCell>
                <TableCell>BTC</TableCell>
                <TableCell>0.005</TableCell>
                <TableCell>Processing</TableCell>
              </TableRow>
              <TableRow>
                <TableCell>
                  <div className="font-semibold"> #111111111</div>
                </TableCell>
                <TableCell>March 1, 2023 14:20:00</TableCell>
                <TableCell>Deposit</TableCell>
                <TableCell>ETH</TableCell>
                <TableCell>0.5</TableCell>
                <TableCell>Completed</TableCell>
              </TableRow>
              <TableRow>
                <TableCell>
                  <div className="font-semibold"> #222222222</div>
                </TableCell>
                <TableCell>March 1, 2023 14:20:00</TableCell>
                <TableCell>Withdrawal</TableCell>
                <TableCell>USDT</TableCell>
                <TableCell>$100.00</TableCell>
                <TableCell>Completed</TableCell>
              </TableRow>
              <TableRow>
                <TableCell>
                  <div className="font-semibold"> #333333333</div>
                </TableCell>
                <TableCell>March 1, 2023 14:20:00</TableCell>
                <TableCell>Deposit</TableCell>
                <TableCell>BTC</TableCell>
                <TableCell>0.01</TableCell>
                <TableCell>Processing</TableCell>
              </TableRow>
            </TableBody>
          </Table>
        </div>
      </CardContent>
    </Card>
  )
}
