/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/MoCsw4v7Hgq
 */
import { CardTitle, CardDescription, CardHeader, CardContent, Card } from "@/components/ui/card"

export function Note() {
  return (
    <Card className="bg-black rounded-lg">
      <CardHeader className="bg-blue-500 rounded-t-lg">
        <CardTitle>Payment outside BinanceFX</CardTitle>
        <CardDescription  className="bg-text-200 " >Please provide your payment details below.</CardDescription>
      </CardHeader>
    </Card>
  )
}
