/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/qeXvh1MlQ7V
 */
import Link from "next/link"

export function WelcomeEmail() {
  return (
    <div className="email bg-gray-100 pt-10 pb-16 md:pt-16 md:pb-24">
      <div className="email-container w-full max-w-screen-sm grid gap-4 px-4 md:gap-8 md:px-8">
        <div className="space-y-2 text-center">
          <img
            alt="Logo"
            className="mx-auto"
            height="64"
            src="/placeholder.svg"
            style={{
              aspectRatio: "64/64",
              objectFit: "cover",
            }}
            width="64"
          />
          <h1 className="text-2xl font-bold leading-none">BINANCE FX INVESTMENT</h1>
        </div>
        <div className="mx-auto grid gap-2 text-sm md:gap-4 md:text-base">
          <div className="grid items-start gap-1.5">
            <p className="text-gray-500">From</p>
            <p className="text-gray-900 font-medium">contact@binancefx.com</p>
          </div>
          <div className="grid items-start gap-1.5">
            <p className="text-gray-500">To</p>
            <p className="text-gray-900 font-medium">example@gmail.com</p>
          </div>
          <div className="grid items-start gap-1.5">
            <p className="text-gray-500">Date</p>
            <p className="text-gray-900 font-medium">Mar 7, 2023, 10:24 AM</p>
          </div>
        </div>
        <hr className="border-t border-gray-200 dark:border-gray-800" />
        <div className="prose max-w-none w-full grid gap-4 text-sm md:text-base">
          <h1 className="text-3xl font-bold tracking-tighter md:text-4xl/tight">Welcome to Binance FX Investment</h1>
          <p>Dear Valued Customer,</p>
          <p>
            We are thrilled to welcome you to Binance FX Investment, your gateway to the world of transparent and secure
            forex trading.
          </p>
          <p>
            At Binance FX Investment, we are committed to providing you with the best trading experience. Our platform
            is designed to offer seamless transactions, real-time market data, and a wide range of trading tools to help
            you make informed investment decisions.
          </p>
          <p>
            Transparency is at the core of our values. You can trust that every transaction you make on our platform is
            secure and transparent. We use the latest technology to ensure the safety of your funds and provide you with
            full visibility into your trading activities.
          </p>
          <p>
            Whether you are a seasoned trader or new to the world of forex trading, Binance FX Investment has everything
            you need to succeed. Our platform is user-friendly, and our customer support team is always here to assist
            you.
          </p>
          <h2 className="text-2xl font-bold tracking-tighter md:text-3xl/tight">Contact Us</h2>
          <p>
            If you have any questions or need assistance, please feel free to contact our customer support team. You can
            reach us via email at
            <a href="#">support@binancefx.com</a>
            or through the live chat feature on our website.
          </p>
          <h2 className="text-2xl font-bold tracking-tighter md:text-3xl/tight">Explore Our Platform</h2>
          <p>
            Ready to start trading? Simply log in to your account on our website to access the trading platform. If you
            haven’t created an account yet, you can sign up on our website.
          </p>
          <div className="grid gap-4">
            <Link
              className="inline-block w-full max-w-xs rounded-lg border border-gray-200 p-2 text-center text-sm transition-colors hover:bg-gray-100 dark:hover:bg-gray-800 dark:border-gray-800"
              href="#"
            >
              Create an Account
            </Link>
            <Link
              className="inline-block w-full max-w-xs rounded-lg border border-gray-200 p-2 text-center text-sm transition-colors hover:bg-gray-100 dark:hover:bg-gray-800 dark:border-gray-800"
              href="#"
            >
              Log In
            </Link>
          </div>
          <p>Thank you for choosing Binance FX Investment.</p>
          <p>Sincerely,</p>
          <p>The Binance FX Investment Team</p>
        </div>
        <div className="grid gap-2 text-sm md:gap-4 md:text-base">
          <div className="grid items-start gap-1.5">
            <p className="text-gray-500">From</p>
            <p className="text-gray-900 font-medium">contact@binancefx.com</p>
          </div>
          <div className="grid items-start gap-1.5">
            <p className="text-gray-500">To</p>
            <p className="text-gray-900 font-medium">example@gmail.com</p>
          </div>
          <div className="grid items-start gap-1.5">
            <p className="text-gray-500">Date</p>
            <p className="text-gray-900 font-medium">Mar 7, 2023, 10:24 AM</p>
          </div>
        </div>
      </div>
    </div>
  )
}
